use_frameworks!

platform :ios, '10.0'

target 'SFBase_Example' do
  pod 'SFBase', :path => '../'

  target 'SFBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
